---
title: "gprofiler_gene_description"
output:
  html_document:
    df_print: paged
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T)
library(gprofiler2)
set_base_url("http://biit.cs.ut.ee/gprofiler_archive3/e100_eg47_p14")
```


```{r get data}
### Get most diversed gene list
dir_in_res = '../out/20.0216 feat/reg_rf_boruta'
dir_in_anlyz = file.path(dir_in_res, 'anlyz_filtered')
f_featsumm = file.path(dir_in_anlyz,'agg_summary_filtered.csv')
df_aggRes = read.csv(f_featsumm) #aggregated feat summary
div_genes = df_aggRes[,1]
```


```{r g:profiler quest, warning = FALSE}
### g:profiler query for the R result
gostres = gost(query = div_genes, organism = "hsapiens", ordered_query = FALSE,
               multi_query = FALSE, significant = TRUE, exclude_iea = FALSE, 
                measure_underrepresentation = FALSE, evcodes = TRUE, 
                user_threshold = 0.05, correction_method = "g_SCS", 
                domain_scope = "annotated", custom_bg = NULL, 
                numeric_ns = "", sources = c('GO:BP', 'GO:CC', 'GO:MF'))

# Save gostres result
write.csv(apply(gostres$result,2,as.character),'target_gores.csv',row.names = FALSE)
```

Interactive plot showing gene description
```{r gprofiler Manhattan plot}
### visulization uncapped interaction plot
p.uncapped = gostplot(gostres, capped = FALSE, interactive = T)
p.uncapped
```


4 out of top5 GO:BP terms are related to cell cycle. These genes include cyclinD gene, cyclin-dependent kinase gene and cell cycle check point.
```{r TOP5 GO:BP term table, warning=FALSE, error=FALSE}
### Get GO:BP dataframe
p = gostplot(gostres, capped =FALSE, interactive = F)
# Get the dataframe of only ordered p-values and GO:BP, GO:CC, GO:MF individual dataframes
gostres.sig = gostres$result[gostres$result$p_value<5e-2,]
gostres.sig = gostres.sig[order(gostres.sig$p_value),]

res.gobp = gostres.sig[grep('GO:BP',gostres.sig$source),]
res.gocc = gostres.sig[grep('GO:CC',gostres.sig$source),]
res.gomf = gostres.sig[grep('GO:MF',gostres.sig$source),]

### Tables for top 5 GO:BP, GO:CC, GO:MF terms
publish_gosttable(gostres, res.gobp[c(1:5),],use_colors = T,
show_columns = c("source", "term_id", "term_name","term_size","intersection_size"),
filename = 'target_bp.pdf')
publish_gosttable(gostres, res.gocc[c(1:5),],use_colors = T,
show_columns = c("source", "term_id", "term_name","term_size","intersection_size"),
filename = 'target_cc.pdf')
publish_gosttable(gostres, res.gomf[c(1:5),],use_colors = T,
show_columns = c("source", "term_id", "term_name","term_size","intersection_size"),
filename = 'target_mf.pdf')

# Plot highlighting top5 terms
p.target = publish_gostplot(p, c(res.gobp$term_id[1:5],res.gocc$term_id[1:5],res.gomf$term_id[1:5]), width = 15, height = 10,filename = 'target_only.pdf')

p.target.all = publish_gostplot(p, width = 9, height = 9,filename = 'target_only.pdf')
```
